name = "snoopy"
uuid = "417cbc22-0cbf-45bf-9611-02e6a703c6cf"
version = "0.1.0"
authors = ["Jeff <strangehurst@gmail.com>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DataTables = "743a1d0a-8ebc-4f23-814b-50d006366bc6"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
PNML = "1f34f301-fe8c-4464-8328-ff2334f05424"
PackageCompatUI = "65465c31-362d-417a-a2f0-7fa38ae507b9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"

[sources]
PNML = {path = "/home/jeff/Jules/PNML"}

[compat]
AbstractTrees = "0.4.5"
Metatheory = "3.0.0"
PrettyTables = "3.0.10"
