name = "notebooks"
uuid = "4a2b1158-5d16-4fce-b6c4-ef74790b0c35"
version = "0.1.0"
authors = ["Jeff Hurst <strangehurst@users.noreply.github.com>"]

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PNML = "1f34f301-fe8c-4464-8328-ff2334f05424"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Catlab = "0.17.4"
DataStructures = "0.18, 0.19"
EzXML = "1"
Graphs = "1.13"
MetaGraphsNext = "0.7.5"
PNML = "0.0.29"
PrecompileTools = "1.3.3"
julia = "1.12"
